### PR TITLE
Use QuantEcon.next_k_array! in support_enumeration

### PR DESCRIPTION
**Pull request by monsij**
Closes Issue #70

All the changes have been made similar to https://github.com/QuantEcon/QuantEcon.py/commit/a215f1f41d312d555b9b2de719ec379bcd16156d

### CODE REVIEW

**Comment by monsij** [comment]
New changes made!  @oyamad

**Comment by sglyon** [comment]
Thank you!

**Comment by sglyon** [comment]
Hi @monsij thanks for the contribution.

I noticed that we still have the routine `_next_k_array!` defined in `src/support_enumeration.jl`. Is this still needed? If not, can we delete it also?

Thanks

**Comment by monsij** [comment]
@sglyon My pleasure!

**Comment by oyamad** [comment]
@monsij Thanks for the PR.

The Python version https://github.com/QuantEcon/QuantEcon.py/commit/a215f1f41d312d555b9b2de719ec379bcd16156d consists of three changes:

1. import `next_k_array`;
2. replace the string `_next_k_array` by `next_k_array`;
3. delete the function definitions of `_next_k_combination` and `_next_k_array`.

This PR does only 2.

@monsij Will you be willing to set up one more pull request to make the other changes?

1. Add

   ```jl
   import QuantEcon: next_k_array!
   ```

   (This seems not to be necessary, but I believe it better to be explicit.)

&

3. Delete the definitions of `_next_k_combination` and `_next_k_array!`.

Thanks!

**Comment by sglyon** [comment]
Thank you @oyamad -- sorry for the pre-mature merge on my part

**Pull request merged**
