### PR TITLE
Get rid of `@generated` for NormalFormGame(payoffs::Array)

### PR DESCRIPTION
**Pull request by oyamad**
By using [`Base.front`](https://github.com/JuliaLang/julia/commit/61836ca3a83750759e0fdeaabc377cb65a01bd17#diff-fd99c9a15dadc23d9200069dadafb8bb) introduced in v0.5.

Address https://github.com/QuantEcon/Games.jl/issues/2#issue-141102799.

### CODE REVIEW

**Comment by oyamad** [comment]
Type inference does not work in v0.5, because of "`Core.Box`":

```
julia> @code_warntype NormalFormGame(zeros(4, 3, 2))
Variables:
  #self#::Type{Games.NormalFormGame}
  payoffs::Array{Float64,3}
  N::Int64
  dims::Core.Box
  colons::Core.Box
  #9::Games.##9#11
  players::AbstractArray{T,N}
  #10::Games.##10#12{Array{Float64,3},Int64}

Body:
  begin 
      dims::Core.Box = $(Expr(:new, :(Core.Box)))
      colons::Core.Box = $(Expr(:new, :(Core.Box)))
      NewvarNode(:(#9::Games.##9#11))
      NewvarNode(:(players::AbstractArray{T,N}))
      NewvarNode(:(#10::Games.##10#12{Array{Float64,3},Int64}))
      N::Int64 = (Base.box)(Int64,(Base.sub_int)($(Expr(:static_parameter, 2)),1)) # line 464:
      # meta: location array.jl size 20
      # meta: location array.jl _size 24
      SSAValue(16) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(0,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(14) = SSAValue(16)
      SSAValue(15) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(1,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(13) = (Core.tuple)(SSAValue(14),SSAValue(15),(Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(2,1)))::Int64)::Tuple{Int64,Int64,Int64}
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      SSAValue(0) = SSAValue(13)
      SSAValue(17) = (Base.nfields)(SSAValue(0))::Int64
      SSAValue(1) = (Base.getfield)(SSAValue(0),SSAValue(17))::Int64
      unless (Base.box)(Base.Bool,(Base.not_int)((SSAValue(1) === N::Int64)::Bool)) goto 25
      (Games.throw)($(Expr(:new, :(Base.ArgumentError), "length of the array in the last axis must be equal to\n         the number of players")))::Union{}
      25:  # line 469:
      # meta: location array.jl size 20
      # meta: location array.jl _size 24
      SSAValue(23) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(0,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(21) = SSAValue(23)
      SSAValue(22) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(1,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(24) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(2,1)))::Int64
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      SSAValue(2) = (Core.tuple)(SSAValue(21),SSAValue(22))::Tuple{Int64,Int64}
      (Core.setfield!)(dims::Core.Box,:contents,SSAValue(2))::Tuple{Int64,Int64} # line 470:
      #9::Games.##9#11 = $(Expr(:new, :(Games.##9#11)))
      SSAValue(3) = #9::Games.##9#11
      SSAValue(4) = $(Expr(:invoke, LambdaInfo for ntuple(::Games.##9#11, ::Int64), :(Games.ntuple), SSAValue(3), :($(Expr(:static_parameter, 2)))))
      SSAValue(5) = Tuple{Colon,Colon,Colon}
      SSAValue(6) = (Core.typeassert)(SSAValue(4),SSAValue(5))::Tuple{Colon,Colon,Colon}
      SSAValue(7) = (Core.tuple)((Core.getfield)(SSAValue(6),1)::Colon,(Core.getfield)(SSAValue(6),2)::Colon)::Tuple{Colon,Colon}
      (Core.setfield!)(colons::Core.Box,:contents,SSAValue(7))::Tuple{Colon,Colon} # line 471:
      #10::Games.##10#12{Array{Float64,3},Int64} = $(Expr(:new, Games.##10#12{Array{Float64,3},Int64}, :(payoffs), :(N), :(dims), :(colons)))
      SSAValue(8) = #10::Games.##10#12{Array{Float64,3},Int64}
      SSAValue(9) = $(Expr(:new, UnitRange{Int64}, 1, :((Base.select_value)((Base.sle_int)(1,N)::Bool,N,(Base.box)(Int64,(Base.sub_int)(1,1)))::Int64)))
      SSAValue(10) = $(Expr(:new, Base.Generator{UnitRange{Int64},Games.##10#12{Array{Float64,3},Int64}}, SSAValue(8), SSAValue(9)))
      players::AbstractArray{T,N} = $(Expr(:invoke, LambdaInfo for collect(::Base.Generator{UnitRange{Int64},Games.##10#12{Array{Float64,3},Int64}}), :(Base.collect), SSAValue(10))) # line 477:
      return (Games.NormalFormGame)(players::AbstractArray{T,N})::Any
  end::Any
```

```
julia> versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, jivybridge)
```

I know how to resolve it actually: it will disappear if one moves [these lines](https://github.com/QuantEcon/Games.jl/blob/a68f36ea5d7b6aa96a93aa7870e72142a057f202/src/normal_form_game.jl#L469-L470) above `size(payoffs)[end] != N ...`. But what is going on?

**Comment by spencerlyon2** [comment]
@oyamad I think this is https://github.com/JuliaLang/julia/issues/15276

**Comment by oyamad** [comment]
Added a workaround for the "Box" problem above, just by changing the order of code lines.

```
julia> @code_warntype NormalFormGame(zeros(4, 3, 2))
Variables:
  #self#::Type{Games.NormalFormGame}
  payoffs::Array{Float64,3}
  N::Int64
  dims::Tuple{Int64,Int64}
  colons::Tuple{Colon,Colon}
  #9::Games.##9#11
  players::Array{Games.Player{2,Float64},1}
  #10::Games.##10#12{Array{Float64,3},Int64,Tuple{Int64,Int64},Tuple{Colon,Colon}}

Body:
  begin 
      NewvarNode(:(players::Array{Games.Player{2,Float64},1}))
      NewvarNode(:(#10::Games.##10#12{Array{Float64,3},Int64,Tuple{Int64,Int64},Tuple{Colon,Colon}}))
      N::Int64 = (Base.box)(Int64,(Base.sub_int)($(Expr(:static_parameter, 2)),1)) # line 455:
      # meta: location array.jl size 20
      # meta: location array.jl _size 24
      SSAValue(14) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(0,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(12) = SSAValue(14)
      SSAValue(13) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(1,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(22) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(2,1)))::Int64
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      dims::Tuple{Int64,Int64} = (Core.tuple)(SSAValue(12),SSAValue(13))::Tuple{Int64,Int64} # line 456:
      #9::Games.##9#11 = $(Expr(:new, :(Games.##9#11)))
      SSAValue(0) = #9::Games.##9#11
      SSAValue(1) = $(Expr(:invoke, LambdaInfo for ntuple(::Games.##9#11, ::Int64), :(Games.ntuple), SSAValue(0), :($(Expr(:static_parameter, 2)))))
      SSAValue(2) = Tuple{Colon,Colon,Colon}
      SSAValue(3) = (Core.typeassert)(SSAValue(1),SSAValue(2))::Tuple{Colon,Colon,Colon}
      colons::Tuple{Colon,Colon} = (Core.tuple)((Core.getfield)(SSAValue(3),1)::Colon,(Core.getfield)(SSAValue(3),2)::Colon)::Tuple{Colon,Colon} # line 458:
      # meta: location array.jl size 20
      # meta: location array.jl _size 24
      SSAValue(20) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(0,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(18) = SSAValue(20)
      SSAValue(19) = (Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(1,1)))::Int64
      # meta: location array.jl _size 24
      SSAValue(17) = (Core.tuple)(SSAValue(18),SSAValue(19),(Base.arraysize)(payoffs::Array{Float64,3},(Base.box)(Int64,(Base.add_int)(2,1)))::Int64)::Tuple{Int64,Int64,Int64}
      # meta: pop location
      # meta: pop location
      # meta: pop location
      # meta: pop location
      SSAValue(4) = SSAValue(17)
      SSAValue(21) = (Base.nfields)(SSAValue(4))::Int64
      SSAValue(5) = (Base.getfield)(SSAValue(4),SSAValue(21))::Int64
      unless (Base.box)(Base.Bool,(Base.not_int)((SSAValue(5) === N::Int64)::Bool)) goto 43
      (Games.throw)($(Expr(:new, :(Base.ArgumentError), "length of the array in the last axis must be equal to\n         the number of players")))::Union{}
      43:  # line 463:
      #10::Games.##10#12{Array{Float64,3},Int64,Tuple{Int64,Int64},Tuple{Colon,Colon}} = $(Expr(:new, Games.##10#12{Array{Float64,3},Int64,Tuple{Int64,Int64},Tuple{Colon,Colon}}, :(payoffs), :(N), :(dims), :(colons)))
      SSAValue(6) = #10::Games.##10#12{Array{Float64,3},Int64,Tuple{Int64,Int64},Tuple{Colon,Colon}}
      SSAValue(7) = $(Expr(:new, UnitRange{Int64}, 1, :((Base.select_value)((Base.sle_int)(1,N)::Bool,N,(Base.box)(Int64,(Base.sub_int)(1,1)))::Int64)))
      SSAValue(8) = $(Expr(:new, Base.Generator{UnitRange{Int64},Games.##10#12{Array{Float64,3},Int64,Tuple{Int64,Int64},Tuple{Colon,Colon}}}, SSAValue(6), SSAValue(7)))
      players::Array{Games.Player{2,Float64},1} = $(Expr(:invoke, LambdaInfo for collect(::Base.Generator{UnitRange{Int64},Games.##10#12{Array{Float64,3},Int64,Tuple{Int64,Int64},Tuple{Colon,Colon}}}), :(Base.collect), SSAValue(8))) # line 469:
      return $(Expr(:invoke, LambdaInfo for Games.NormalFormGame{N,T<:Real}(::Tuple{Games.Player{2,Float64},Games.Player{2,Float64}}), :(Games.NormalFormGame), :((Core.typeassert)((Core._apply)(Games.tuple,players)::Tuple{Vararg{Games.Player{2,Float64},N}},Tuple{Games.Player{2,Float64},Games.Player{2,Float64}})::Tuple{Games.Player{2,Float64},Games.Player{2,Float64}})))
  end::Games.NormalFormGame{2,Float64}
```

**Comment by oyamad** [comment]
Let me merge this.

**Pull request merged**
