### PR TITLE
Use QuantEcon.next_k_array! in support_enumeration

### PR DESCRIPTION
**Pull request by monsij**
Closes issue #70 
The remaining changes have been made mentioned in the [comment-link](https://github.com/QuantEcon/Games.jl/pull/81#issuecomment-392622366). Kindly let me know if the changes in docstrings are also required.
@sglyon @oyamad

### CODE REVIEW

**Comment by oyamad** [comment]
@monsij Thanks.

* Yes, please delete the docstrings of `_next_k_combination` and `_next_k_array!`.
* Please do not delete blank lines in other docstrings. See the [changes](https://github.com/monsij/Games.jl/commit/9a1582bf2d1b761e4e9b57637086aa128a336079) you made.

**Comment by monsij** [comment]
It's done ! 🎉 @oyamad  @sglyon

**Comment by oyamad** [comment]
Great, thanks!

**Comment by monsij** [comment]
My pleasure!

**Pull request merged**
