### PR TITLE
is_dominated: Use MathOptInterface in place of MathProgBase

### LINKED ISSUE #108: UndefVarError: CDDSolver not defined
```jl
include("test_normal_form_game.jl")
```

```
...
  Got exception outside of a @test
  UndefVarError: CDDSolver not defined
...
```

### PR DESCRIPTION
**Pull request by oyamad**
Close #108

Here is my proposal regarding LP solver. One disadvantage is the dependency on `JuMP` despite the only use of `JuMP.OptimizerFactory` and `JuMP.with_optimizer`.

### CODE REVIEW

**Comment by Yuya-Furusawa** [comment]
In addition, I rewrite repeated_game.jl with `MathOptInterface`.

https://github.com/Yuya-Furusawa/Games.jl/blob/UseMOI/src/repeated_game.jl

I could initialize MOI instance with `MOI.empty!`.
But we can also use `with_optimizer` to do this.

Related discussion is here(This is also my issue in Julia discourse)
https://discourse.julialang.org/t/best-practice-to-solve-optimization-problem-repeatedly-in-a-function-with-mathoptinterface/23592

**Comment by oyamad** [comment]
@Yuya-Furusawa Thanks, I didn't realize those discussions.

Regarding your code in `normal_form_game.jl`:
1. Does it work with `CDDLib.Optimizer{BigInt}` for exact arithmetic?
2. For `dominated_actions`, you have to initialize the optimizer in `is_dominated` or `dominated_actions`.

**Comment by oyamad** [comment]
Another option is to let `lp_solver::Union{MOI.AbstractOptimizer,Function}`: One can pass an optimizer type (such as `Clp.Optimizer`) if no option is needed, or a closure (such as `() -> Clp.Optimizer(LogLevel=0)`) to supply options.

**Comment by Yuya-Furusawa** [comment]
> Does it work with `CDDLib.Optimizer{BigInt}` for exact arithmetic?

No. This error is because, I think, type `S` in my code conflicts `BigInt` and `MOI` does not support. I will fix this bug.

>  For `dominated_actions`, you have to initialize the optimizer in `is_dominated` or `dominated_actions`.

Exactly, I will fix it.

I think in users' point of view, it is not intuitive to put an `::Type` as an input. It is better to make it optional argument.

**Pull request merged**
